"""Add pattern_rounds table

Revision ID: 38592f72dbaf
Revises: 7af320917e2e
Create Date: 2025-07-11 18:02:18.045280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38592f72dbaf'
down_revision: Union[str, Sequence[str], None] = '7af320917e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pattern_rounds', sa.Column('round_number', sa.Integer(), nullable=False))
    op.add_column('pattern_rounds', sa.Column('correct_streak_at_time', sa.Integer(), nullable=True))
    op.add_column('pattern_rounds', sa.Column('max_streak_so_far', sa.Integer(), nullable=True))
    op.add_column('pattern_rounds', sa.Column('projected_final_score', sa.Integer(), nullable=True))
    op.alter_column('pattern_rounds', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pattern_rounds', 'round')
    op.drop_column('pattern_rounds', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pattern_rounds', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pattern_rounds', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('pattern_rounds', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pattern_rounds', 'projected_final_score')
    op.drop_column('pattern_rounds', 'max_streak_so_far')
    op.drop_column('pattern_rounds', 'correct_streak_at_time')
    op.drop_column('pattern_rounds', 'round_number')
    # ### end Alembic commands ###
